name: reel_deal
description: An app to help users pick movies and TV shows based on mood and preferences.
publish_to: 'none'
version: 1.3.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  flutter_launcher_icons: ^0.14.3
  lottie: ^2.7.0
  youtube_player_flutter: 9.1.1
  flutter_rating_bar: ^4.0.1
  flutter_inappwebview: ^6.1.0
  connectivity_plus: ^4.0.2
  shimmer: ^3.0.0
  youtube_player_iframe: ^4.0.4





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/empty.json


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#FFFFFF" # or an image path
  adaptive_icon_foreground: "assets/icon/foreground.png"

